import Head from 'next/head'
import { Box } from '@mui/system';
import Layout from '../src/Layout/Layout';
import HomeComponent from '../src/components/Home/Home';
import SendData from '../src/documents/Reusiable/DispatchData/DispatchData';

export default function Home() {
    SendData()
    return (
        <Box>
            <Head>
                <title>Asosiy Sahifa</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <HomeComponent/>
            </Layout>
        </Box>
    )
}
