import Head from 'next/head'
import {Box} from "@mui/system";
import Layout from "../src/Layout/Layout";
import Profile from "../src/components/Profile/Profile";

export default function profile() {
    return (
        <Box>
            <Head>
                <title>Mening Profilm </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Layout>
               <Profile />
            </Layout>
        </Box>
    )
}
