import Head from 'next/head'
import {Box} from "@mui/system";
import Layout from "../src/Layout/Layout";
import SearchData from "../src/components/SearchData/SearchData";

export default function Search() {
    return (
        <Box>
            <Head>
                <title>Topilgan mahsulotlar</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <SearchData />
            </Layout>
        </Box>
    )
}
