import Head from 'next/head'
import {Box} from "@mui/system";
import Layout from "../src/Layout/Layout";
import SingleProduct from "../src/documents/Reusiable/SingleProduct/SingleProduct";

export default function Home() {
    return (
        <Box>
            <Head>
                <title>Mahsulot haqida</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <SingleProduct />
            </Layout>
        </Box>
    )
}
