import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    summaryWrapper: {
        maxWidth: '397px',
        height: 'auto',
        borderRadius: '10px',
        background: '#fff',
        padding: '50px 20px',
        marginLeft: '20px',
        width: '100%',
        '@media(max-width: 650px)': {
            padding: '20px 10px',
            marginLeft: 0,
            marginTop: '20px',
        },
    },
    quantity: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '30px 0',
        gap: '40px',
    },
    quant: {
        fontSize: '22px',
        lineHeight: '24px',
    },
    sticky: {
        maxWidth: '397px',
        height: 'auto',
        borderRadius: '10px',
        background: '#fff',
        padding: '50px 20px',
        marginLeft: '20px',
        width: '100%',
        position: 'sticky',
        top: '85px',
        '@media(max-width: 650px)': {
            position: 'static',
            padding: '20px 10px',
            marginLeft: 0,
            marginTop: '20px',
        },
    },
    name: {
        fontSize: '28px',
        fontWeight: 600,
        lineHeight: '33.6px',
    },
    total: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        padding: '27px 0 10px 0',
        borderBottom: '1px dashed #E4E7EE',
    },
    delivery: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        padding: '27px 0 10px 0',
        borderBottom: '1px solid #E4E7EE',
    },
    summa: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px 0 10px 0',
    },
    text: {
        fontSize: '14px',
        lineHeight: '16px',
        color: '#455262',
    },
    price: {
        fontSize: '22px',
        lineHeight: '26px',
        fontWeight: 600,
        paddingLeft: '41px'
    },
    textCenter: {
        fontSize: '14px',
        lineHeight: '16px',
        color: '#455262',
        textAlign: 'center',
    },
    priceCenter: {
        fontSize: '22px',
        lineHeight: '26px',
        fontWeight: 600,
        paddingLeft: 0,
        textAlign: 'center',
        marginTop: '20px',
    },
    buyBtn: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
        maxWidth: '250px',
        height: '64px',
        margin: '30px auto 0 auto',
    },
    submitButton: {
        width: '100%',
        height: '100%',
        background: '#0D63F3',
        color: '#fff',
        padding: '10px 0',
        '&:hover': {
            opacity: 0.8,
            background: '#0D63F3 !important',
        },
        '@media(max-width: 650px)': {
            fontSize: '12px',
            fontWeight: 400,
        },
    },
    successWrapper: {
        maxWidth: '397px',
        height: '500px',
        borderRadius: '10px',
        background: '#fff',
        padding: '50px 20px',
        marginLeft: '20px',
        width: '100%',
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        // justifyContent: "center",
        '@media(max-width: 650px)': {
            padding: '20px 10px',
            marginLeft: 0,
            marginTop: '20px',
            height: "auto",
        },
    },
    successText: {
        margin: "30px 0",
        fontSize: "26px",
        lineHeight: "32px",
        fontWeight:600,
        textAlign: "center",
    },
    successSub: {
        fontSize: "18px",
        lineHeight: "20px",
        fontWeight:500,
        textAlign: "center",
    },
    successOrdinaryText: {
        fontSize: "16px",
        lineHeight: "16px",
        fontWeight:500,
        textAlign: "center",
        margin: "30px 0",
        color: "#6C757D",
        width: '500px',
    },
    successOrdinaryTextColor:{
        color: "#0D63F3",
        cursor: "pointer",
    },
    successButton: {
        height: "40px",
        width: "70%",
    },

    successIcon: {
        width: "90px",
        height: '90px',
        background: "#DFF3D5",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "50%",
    },
    verifiedIcon: {
        fontSize: "2rem",
        color: "#369609",
    },
}))
