import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    head: {
        position: 'relative',
    },
    swiper: {
        maxWidth: "1230px",
        margin: "0 auto",
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        marginBottom: '4%',
        borderRadius: '8px',
        '--swiper-pagination-color': '#fff !important',
        '--swiper-navigation-color': '#fff !important',
        '@media(max-width: 650px)': {
            maxWidth: "380px",
            marginBottom: "10%",
            flexDirection: 'column',
            alignItems: 'center',
            padding: '10px 0',
            justifyContent: "center",
        },
    },
    slide:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: "space-evenly",
        '@media(max-width: 650px)': {
            flexDirection: 'column',
            justifyContent: "center",
        },
    },
    navigateIcon: {
        color: '#fff',
        marginTop: '8px',
        fontSize: '17px',
        marginLeft: '5px',
    },
    arrowBack: {
        background: 'linear-gradient(to right, #4D5EF6, #F64D4D)',
        position: 'absolute',
        left: '-50px',
        top: '45%',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        border: 'none',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        cursor: 'pointer',
        '@media(max-width: 1230px)': {
            left: 3,
            top: '40%',
            zIndex: 2,
            background: 'transparent',
        },
    },
    arrowBackPrimary: {
        background: '#0D63F3',
        position: 'absolute',
        left: '-50px',
        top: '45%',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        border: 'none',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        cursor: 'pointer',
        '@media(max-width: 1230px)': {
            left: 3,
            top: '40%',
            zIndex: 2,
            background: 'transparent',
        },
    },
    arrowForwardPrimary: {
        background: '#0D63F3',
        position: 'absolute',
        right: '-50px',
        top: '45%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        border: 'none',
        cursor: 'pointer',
        '@media(max-width: 1230px)': {
            right: 3,
            bottom: '50%',
            zIndex: 2,
            background: 'transparent',
        },
    },
    arrowForward: {
        background: 'linear-gradient(to right, #4D5EF6, #F64D4D)',
        position: 'absolute',
        right: '-50px',
        top: '45%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        border: 'none',
        cursor: 'pointer',
        '@media(max-width: 1230px)': {
            right: 3,
            top: '40%',
            zIndex: 2,
            background: 'transparent',
        },
    },
    textContent: {
        '@media(max-width: 650px)': {
            maxWidth: '250px',
            margin: '0 auto',
        },
    },

    title: {
        fontSize: '54px',
        lineHeight: '50px',
        color: '#fff',
        maxWidth: "600px",
        marginTop: "-10px",
        '@media(max-width: 650px)': {
            fontSize: '25px',
            lineHeight: '28px',
            color: '#fff',
            maxWidth: '300px',
        },
    },
    textTop: {
        fontSize: '54px',
        lineHeight: '50px',
        color: '#fff',
        maxWidth: "600px",
        marginTop: "-50px",
        '@media(max-width: 650px)': {
            fontSize: '28px',
            lineHeight: '30px',
            color: '#fff',
            maxWidth: '300px',
        },
    },
    sub: {
        fontSize: '18px',
        color: '#fff',
        marginTop: '20px',
        '@media(max-width: 650px)': {
            fontSize: '16px',
        },
    },
    images: {
        objectFit: 'contain',
        '@media(max-width: 650px)': {
            display: 'none',
        },
    },
    showImage: {
        objectFit: 'contain',
    },
    buttons: {
        position: "absolute",
        bottom: "30px",
        left: "110px",
        width: "200px",
        height: '54px',
        background: "#0D63F3",
        color: "#fff",
        '&:hover': {
            background: '#0D63F3 !important',
            opacity: 0.9,
        },
        '@media(max-width: 650px)': {
            left: "90px",
             height: '48px',
            width: "180px",
        },
    },
}))
